### PR TITLE
Add unit testing and codecov support

### PR DESCRIPTION
**Pull request by dagwieers**
This PR includes:
- Ignore exporting certain files (using .gitattributes)
- Add unittest framework for Kodi
- Add tests/run.py for command-line testing
- Add basic routing tests to get basic run coverage
- Add codecov and SonarCloud support
- Add tox and pylint validation
- Add GitHub CI workflows for add-on and unit tests
- Removed Travis support
- Various basic fixes for tox and pylint
- Added badges for coverage and GitHub CI build result

### CODE REVIEW

**Comment by dagwieers** [comment]
The PR requires adding a GitHub secret `SONAR_TOKEN` to get SonarCloud support.

The GitHub CI results (when integrated) look like this:
https://github.com/dagwieers/plugin.video.fosdem/actions

The Codecov results (when integrated) look like this:
https://codecov.io/gh/dagwieers/plugin.video.fosdem

The SonarCloud results (when integrated) look like this:
https://sonarcloud.io/dashboard?id=dagwieers_plugin.video.fosdem

**Comment by dagwieers** [comment]
These are the badges added:
[GitHub release](https://github.com/jelly/plugin.video.fosdem/releases)
[Build status](https://github.com/dagwieers/plugin.video.fosdem/actions)
[Codecov status](https://codecov.io/gh/dagwieers/plugin.video.fosdem/branch/master)
[License: MIT](https://opensource.org/licenses/MIT)
[Contributors](https://github.com/jelly/plugin.video.fosdem/graphs/contributors)

**Comment by jelly** [comment]
I was under the impression that python2 was no longer support by Kodi or in the future, so why add backwards compatibility?

**Comment by dagwieers** [comment]
Matrix has not been released, so you want to drop support for the thing that most people are still using?

**Comment by jelly** [comment]
> Matrix has not been released, so you want to drop support for the thing that most people are still using?

Well I am a bit confused as you add from __future__ import foo, as this wasn't there before so I assume it worked on python2 :-)

> BTW I am not adding backwards compatibility, I am testing against currently supported environments. Which is Krypton and Leia (python 2) and Matrix (python 3).

Hmm no it's fine.

**Comment by dagwieers** [comment]
@jelly This is added to silence pylint, but is a common practice for code that is targeting Python 3 first, and Python 2 second. (which is why pylint checks for this)

**Comment by dagwieers** [comment]
Most of the testing snippets here comes from the Kodi Add-ons project, which is what we use as a best-practice for automated testing. Let me invite you to that project.

**Comment by dagwieers** [comment]
With this PR you can do functional testing outside of Kodi like this:
```
[dag@moria plugin.video.fosdem]$ ./tests/run.py /day/2020/1
** Running URI plugin://plugin.video.fosdem/day/2020/1 with args 
Debug: [plugin.video.fosdem][routing] Dispatching to 'show_day', args: {u'day': u'1', u'year': u'2020'}
» Janson - Keynotes → /room/2020/1/Janson
» K.1.105 (La Fontaine) - Community and Ethics → /room/2020/1/K.1.105 (La Fontaine)
» H.2215 (Ferrer) - Lightning Talks → /room/2020/1/H.2215 (Ferrer)
» H.1302 (Depage) - Free Java → /room/2020/1/H.1302 (Depage)
» H.1308 (Rolin) - Software Defined Networking → /room/2020/1/H.1308 (Rolin)
» H.1309 (Van Rijn) - DNS → /room/2020/1/H.1309 (Van Rijn)
» H.2213 - Open Source Computer Aided Modeling and Design → /room/2020/1/H.2213
» H.2214 - MySQL, MariaDB and Friends → /room/2020/1/H.2214
» AW1.120 - Collaborative Information and Content Management Applications → /room/2020/1/AW1.120
» AW1.121 - Erlang, Elixir and Friends → /room/2020/1/AW1.121
» AW1.125 - Ada → /room/2020/1/AW1.125
» AW1.126 - Open Research Tools and Technologies → /room/2020/1/AW1.126
» K.3.201 - Game Development → /room/2020/1/K.3.201
» K.3.401 - RISC-V → /room/2020/1/K.3.401
» K.4.201 - LLVM → /room/2020/1/K.4.201
» K.4.401 - Graphics → /room/2020/1/K.4.401
» K.4.601 - Hardware-aided Trusted Computing → /room/2020/1/K.4.601
» UA2.114 (Baudoux) - Security → /room/2020/1/UA2.114 (Baudoux)
» UA2.118 (Henriot) - Quantum Computing → /room/2020/1/UA2.118 (Henriot)
» UA2.220 (Guillissen) - Legal and Policy Issues → /room/2020/1/UA2.220 (Guillissen)
» UB2.147 - Testing and Automation → /room/2020/1/UB2.147
» UB2.252A (Lameere) - Python → /room/2020/1/UB2.252A (Lameere)
» UB4.136 - Open Document Editors → /room/2020/1/UB4.136
» UD2.119 - Backup and Recovery → /room/2020/1/UD2.119
» UD2.120 (Chavanne) - Infra Management → /room/2020/1/UD2.120 (Chavanne)
» UD2.208 (Decroly) - Containers → /room/2020/1/UD2.208 (Decroly)
» UD2.218A - Embedded, Mobile and Automotive → /room/2020/1/UD2.218A
```

**Comment by dagwieers** [comment]
Feel free to merge this, in case I find anything more to improve I will do so in another PR.
As this PR helps me work on the add-on without the need to have to test on Kodi itself.

**Comment by dagwieers** [comment]
I would like to work on Search capabilities en Up Next integration, but I now already have 3 branches open and prefer to see this functionality integrated without too many conflicts.

And I need this PR merged for testing anyhow.

**Comment by jelly** [comment]
I hope to take a look this weekend, but can't make any promises.

**Comment by jelly** [comment]
Tested it locally, I of course had to make a virtualenv which as I don't have these modules locally and a small issue is that flake8 run by tox also checks "env" which is my virtualenv.

**Comment by dagwieers** [comment]
I don't fully understand what you mean. Can you give the output or an error message?
Running `pip install -r requirements.txt` should install everything you need for running these tests.

Even though running the different routes already gets us at 95% coverage, we probably want to add unit-tests for the handful of functions and test input/output for each.

The existing integration tests don't test conformity, it simply runs 95% of the code paths to ensure there are no failures for those (deterministic) routes. We may want to add routes for known failure paths too to test the behaviour (I made some fixes in another PR wrt. events with no videos)

**Comment by dagwieers** [comment]
In any case the tests run fine in GitHub CI, which is the most important use-case IMO.

**Pull request merged**
